DROP TABLE BOARD;
DROP TABLE MEMBER;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ  START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE TABLE MEMBER (
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) NOT NULL UNIQUE,
	MPW VARCHAR2(30) NOT NULL,
	MNAME VARCHAR2(30) NOT NULL,
	MEMAIL VARCHAR2(200) NOT NULL UNIQUE,
	MPHONE VARCHAR2(20), 
	MADDRESS VARCHAR2(200),
	MREGDATE DATE
);

CREATE TABLE BOARD (
	BNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) REFERENCES MEMBER (MID),
	BTITLE VARCHAR2(1000) NOT NULL,
	BCONTENT VARCHAR2(4000),
	BFILENAME VARCHAR2(1000),
	BPW VARCHAR2(30),
	BIP VARCHAR2(30),	-- 작성IP
	BHIT NUMBER DEFAULT 0,		
	BLASTMODIFY DATE DEFAULT SYSDATE,	-- 최종 수정일
	BREGDATE DATE DEFAULT SYSDATE,		-- 최초 작성일
	BDELETE NUMBER DEFAULT 0,			-- 삭제여부	(삭제: -1, 정상: 0)
	BGROUP NUMBER,		-- 게시글 그룹 (어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	BGROUPORD NUMBER,	-- 게시글 순서 (같은 그룹에서 표시할 순서)
	BDEPTH NUMBER		-- 게시글/댓글 구분 (게시글: 0, 댓글: 1 이상)
);

INSERT INTO BOARD(NO, TITLE, USER_ID, CONTENT)
	VALUES(BOARD_SEQ.NEXTVAL, '총 균 쇠', '에밀리','인간의 문명에 관한 인류사 장르의 책');
INSERT INTO BOARD(NO, TITLE, USER_ID, CONTENT)
	VALUES(BOARD_SEQ.NEXTVAL, '안나 카레니나', '앨리스','행복한 가장은 모두 비슷하지만 불행한 가정은 저마다의 이유가 있다.');
INSERT INTO BOARD(NO, TITLE, USER_ID, CONTENT)
	VALUES(BOARD_SEQ.NEXTVAL, '닥터 프로스트', '제임스','극복하지 못하면 닮아간다.');
	
SELECT * FROM BOARD;
SELECT * FROM MEMBER;

